export const ProductCategoryEnum = {
  ["디지털기기"]: "digitalDevice",
  ["생활가전"]: "householdAppliances",
  ["가구/인테리어"]: "furniture/interior",
  ["생활/주방"]: "dailySupplies/kitchenUtensils",
  ["유아동"]: "infant",
  ["유아도서"]: "kidsBook",
  ["여성의류"]: "femaleFashion",
  ["여성잡화"]: "femaleSundries",
  ["남성패션/잡화"]: "maleFashion/maleSundries",
  ["뷰티/미용"]: "beautyCare",
  ["스포츠/레저"]: "sports/leisure",
  ["취미/게임/음반"]: "hobby/game/record",
  ["도서"]: "book",
  ["티켓/교환권"]: "ticket/coupon",
  ["가공식품"]: "processedFood",
  ["반려동물용품"]: "petSupplies",
  ["식물"]: "plant",
  ["기타 중고물품"]: "etc",
  ["삽니다"]: "buy",
} as const;

export type ProductCategoryEnum = typeof ProductCategoryEnum[keyof typeof ProductCategoryEnum];

export const ProductCategory: { text: keyof typeof ProductCategoryEnum; value: ProductCategoryEnum; feedback: string[] }[] = [
  { text: "디지털기기", value: "digitalDevice", feedback: [] },
  { text: "생활가전", value: "householdAppliances", feedback: [] },
  { text: "가구/인테리어", value: "furniture/interior", feedback: [] },
  { text: "생활/주방", value: "dailySupplies/kitchenUtensils", feedback: [] },
  { text: "유아동", value: "infant", feedback: [] },
  { text: "유아도서", value: "kidsBook", feedback: [] },
  { text: "여성의류", value: "femaleFashion", feedback: [] },
  { text: "여성잡화", value: "femaleSundries", feedback: [] },
  { text: "남성패션/잡화", value: "maleFashion/maleSundries", feedback: [] },
  { text: "뷰티/미용", value: "beautyCare", feedback: [] },
  { text: "스포츠/레저", value: "sports/leisure", feedback: [] },
  { text: "취미/게임/음반", value: "hobby/game/record", feedback: [] },
  { text: "도서", value: "book", feedback: [] },
  { text: "티켓/교환권", value: "ticket/coupon", feedback: [] },
  { text: "가공식품", value: "processedFood", feedback: [] },
  { text: "반려동물용품", value: "petSupplies", feedback: [] },
  { text: "식물", value: "plant", feedback: [] },
  { text: "기타 중고물품", value: "etc", feedback: [] },
  { text: "삽니다", value: "buy", feedback: [] },
];
