export const ProductCategoryEnum = {
  ["디지털기기"]: "digital-device",
  ["생활가전"]: "home-appliances",
  ["가구/인테리어"]: "furniture/interior",
  ["생활/주방"]: "life/kitchen",
  ["유아동"]: "infant",
  ["유아도서"]: "children-book",
  ["여성의류"]: "female-fashion",
  ["여성잡화"]: "female-sundries",
  ["남성패션/잡화"]: "male-fashion/male-sundries",
  ["뷰티/미용"]: "beauty/cosmetology",
  ["스포츠/레저"]: "sports/leisure",
  ["취미/게임/음반"]: "hobby/game/album",
  ["도서"]: "book",
  ["티켓/교환권"]: "ticket/coupon",
  ["가공식품"]: "processed-food",
  ["반려동물용품"]: "companion-animal-supplies",
  ["식물"]: "plant",
  ["기타 중고물품"]: "etc",
  ["삽니다"]: "require",
} as const;

export type ProductCategoryEnum = typeof ProductCategoryEnum[keyof typeof ProductCategoryEnum];

export const ProductCategory: { text: keyof typeof ProductCategoryEnum; value: ProductCategoryEnum; feedback: string[] }[] = [
  { text: "디지털기기", value: "digital-device", feedback: [] },
  { text: "생활가전", value: "home-appliances", feedback: [] },
  { text: "가구/인테리어", value: "furniture/interior", feedback: [] },
  { text: "생활/주방", value: "life/kitchen", feedback: [] },
  { text: "유아동", value: "infant", feedback: [] },
  { text: "유아도서", value: "children-book", feedback: [] },
  { text: "여성의류", value: "female-fashion", feedback: [] },
  { text: "여성잡화", value: "female-sundries", feedback: [] },
  { text: "남성패션/잡화", value: "male-fashion/male-sundries", feedback: [] },
  { text: "뷰티/미용", value: "beauty/cosmetology", feedback: [] },
  { text: "스포츠/레저", value: "sports/leisure", feedback: [] },
  { text: "취미/게임/음반", value: "hobby/game/album", feedback: [] },
  { text: "도서", value: "book", feedback: [] },
  { text: "티켓/교환권", value: "ticket/coupon", feedback: [] },
  { text: "가공식품", value: "processed-food", feedback: [] },
  { text: "반려동물용품", value: "companion-animal-supplies", feedback: [] },
  { text: "식물", value: "plant", feedback: [] },
  { text: "기타 중고물품", value: "etc", feedback: [] },
  { text: "삽니다", value: "require", feedback: [] },
];
